package top.sunriseydy.syhthems.db.mapper;

import top.sunriseydy.syhthems.db.base.CustomBaseMapper;
import top.sunriseydy.syhthems.db.model.Menu;

/**
 * @author SunriseYDY
 * Generated by MBG
 */
public interface MenuMapper extends CustomBaseMapper<Menu> {
}