package top.sunriseydy.syhthems.db.mapper;

import top.sunriseydy.syhthems.db.base.CustomBaseMapper;
import top.sunriseydy.syhthems.db.model.Role;

/**
 * @author SunriseYDY
 * Generated by MBG
 */
public interface RoleMapper extends CustomBaseMapper<Role> {
}