package top.sunriseydy.syhthems.db.mapper;

import top.sunriseydy.syhthems.db.base.CustomBaseMapper;
import top.sunriseydy.syhthems.db.model.UserRole;

/**
 * @author SunriseYDY
 * Generated by MBG
 */
public interface UserRoleMapper extends CustomBaseMapper<UserRole> {
}