package top.sunriseydy.syhthems.db.model;

import lombok.Data;

import javax.persistence.*;

/**
 * @author SunriseYDY
 * Generated by MBG
 */
@Data
@Table(name = "`sys_role_menu`")
public class RoleMenu extends BaseModel {
    @Id
    @Column(name = "`srm_id`")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long srmId;

    /**
     * 角色id
     */
    @Column(name = "`role_id`")
    private Long roleId;

    /**
     * 菜单id
     */
    @Column(name = "`menu_id`")
    private Long menuId;

    public static final String SRM_ID = "srmId";

    public static final String DB_SRM_ID = "srm_id";

    public static final String ROLE_ID = "roleId";

    public static final String DB_ROLE_ID = "role_id";

    public static final String MENU_ID = "menuId";

    public static final String DB_MENU_ID = "menu_id";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";

    public static final String LAST_UPDATE_TIME = "lastUpdateTime";

    public static final String DB_LAST_UPDATE_TIME = "last_update_time";

    public static final String LAST_UPDATE_BY = "lastUpdateBy";

    public static final String DB_LAST_UPDATE_BY = "last_update_by";
}