package top.sunriseydy.syhthems.db.model;

import lombok.Data;

import javax.persistence.*;

/**
 * @author SunriseYDY
 * Generated by MBG
 */
@Data
@Table(name = "`sys_user_role`")
public class UserRole extends BaseModel {
    @Id
    @Column(name = "`sur_id`")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long surId;

    /**
     * 用户id
     */
    @Column(name = "`user_id`")
    private Long userId;

    /**
     * 角色id
     */
    @Column(name = "`role_id`")
    private Long roleId;

    public static final String SUR_ID = "surId";

    public static final String DB_SUR_ID = "sur_id";

    public static final String USER_ID = "userId";

    public static final String DB_USER_ID = "user_id";

    public static final String ROLE_ID = "roleId";

    public static final String DB_ROLE_ID = "role_id";

    public static final String CREATE_TIME = "createTime";

    public static final String DB_CREATE_TIME = "create_time";

    public static final String LAST_UPDATE_TIME = "lastUpdateTime";

    public static final String DB_LAST_UPDATE_TIME = "last_update_time";

    public static final String LAST_UPDATE_BY = "lastUpdateBy";

    public static final String DB_LAST_UPDATE_BY = "last_update_by";
}